### ISSUE TITLE
[Bug] Failing to copy text in Linux

### ISSUE THREAD

**Issue by rileyhawk1417** [BringingFire/rich_clipboard#11]
Ran the example project and this error came up, the rich_clipboard example closes when I try to copy the text.
Paste has no issues, but I tried to copy the text I just pasted and it came up as null.

```
** (example:259150): CRITICAL **: 14:18:14.292: const gchar *fl_value_get_string(FlValue *): assertion 'self->type == FL_VALUE_TYPE_STRING' failed
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
Lost connection to device.
```

**Comment by jmatth** [comment]
Thanks for the bug report. I have a fix on a branch [here][1]. Can you pull that and confirm if the fix works for you?

[1]: https://github.com/BringingFire/rich_clipboard/tree/feature/fix-linux-copy

**Comment by rileyhawk1417** [comment]
Hi @jmatth  thanks for responding. Just tested it, doesn't crash like before after pressing copy but throws this error.

```
** (example:14886): CRITICAL **: 05:39:39.195: const gchar *fl_value_get_string(FlValue *): assertion 'self->type == FL_VALUE_TYPE_STRING' failed

** (example:14886): CRITICAL **: 05:39:58.928: const gchar *fl_value_get_string(FlValue *): assertion 'self->type == FL_VALUE_TYPE_STRING' failed

** (example:14886): WARNING **: 05:40:10.107: Unable to retrieve framework response: Message is not valid JSON
```

Had used this text to paste and try to copy it back ``👋 Hello There How are you!``. 
So not sure if it's selective of the text that comes in, because HTML is empty.
I tried pasting some text from an HTML page and it just worked without any errors.

**Comment by jmatth** [comment]
I just updated the branch with code that should fix that issue as well. Can you pull it and let me know if you see any more issues?

**Comment by rileyhawk1417** [comment]
Hey thanks the fix helped solve the copy issue :D

**Comment by jmatth** [comment]
The fix should now be live on pub.dev
