### ISSUE TITLE
Needs update

### ISSUE THREAD

**Issue by MalikSamiAwan** [BringingFire/rich_clipboard#12]
Because file_picker >=5.0.0 depends on ffi ^2.0.1 and every version of rich_clipboard_windows depends on ffi ^1.1.2, file_picker >=5.0.0 is incompatible with rich_clipboard_windows.
And because rich_clipboard >=1.0.0 depends on rich_clipboard_windows ^1.0.0, file_picker >=5.0.0 is incompatible with rich_clipboard >=1.0.0.
So, because hatchapp depends on both rich_clipboard ^1.0.1 and file_picker ^5.0.1, version solving failed.
pub get failed (1; So, because hatchapp depends on both rich_clipboard ^1.0.1 and file_picker ^5.0.1, version solving failed.)

**Comment by jmatth** [comment]
Thanks for the report. Version `1.0.1` should be available on pub.dev with the fix now.
