### ISSUE TITLE
Characters outside of BMP are copied separately by their surrogate pair

### ISSUE THREAD

**Issue by harkairt** [BringingFire/rich_clipboard#14]
<details>
  <summary>Example code for reproduction</summary>

  ```
  import 'package:flutter/material.dart';
  import 'package:rich_clipboard/rich_clipboard.dart';

  void main() {
    runApp(const MyApp());
  }

  class MyApp extends StatelessWidget {
    const MyApp({super.key});

    @override
    Widget build(BuildContext context) {
      final sourceController = TextEditingController(text: "😊☺️😢🤔❤️🌼👍🤝👏✔️☀️⭐");
      final destinationController = TextEditingController();
      destinationController.addListener(() {
        debugPrint('Destination codeUnits');
        debugPrint(destinationController.text.codeUnits.join(', '));
        debugPrint('');

        // Uncomment this to crash the app when pasting certain emojies
        // debugPrint(destinationController.text.characters.toString());
      });

      return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          body: Padding(
            padding: const EdgeInsets.all(16),
            child: Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Expanded(
                        child: TextField(controller: sourceController),
                      ),
                      IconButton(
                        onPressed: () async {
                          await RichClipboard.setData(
                            RichClipboardData(text: sourceController.text),
                          );
                          debugPrint('Source text');
                          debugPrint(sourceController.text);
                          debugPrint('Source codeUnits');
                          debugPrint(sourceController.text.codeUnits.join(', '));
                        },
                        icon: const Icon(Icons.copy),
                      )
                    ],
                  ),
                  Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      IconButton(
                        onPressed: () async {
                          final clipboardData = await RichClipboard.getData();
                          destinationController.text = clipboardData.text ?? "Cannot get clipboard content (null)";
                        },
                        icon: const Icon(Icons.arrow_right_alt),
                      ),
                      Expanded(child: TextField(controller: destinationController)),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
      );
    }
  }
  ```
</details>

1. Click on the copy icon
2. Click on the ➡️ icon

Debug output:

```
Source text
😊☺️😢🤔❤️🌼👍🤝👏✔️☀️⭐
Source codeUnits
55357, 56842, 9786, 65039, 55357, 56866, 55358, 56596, 10084, 65039, 55356, 57148, 55357, 56397, 55358, 56605, 55357, 56399, 10004, 65039, 9728, 65039, 11088
Destination codeUnits
65533, 65533, 9786, 65039, 65533, 65533, 65533, 65533, 10084, 65039, 65533, 65533, 65533, 65533, 65533, 65533, 65533, 65533, 10004, 65039, 9728, 65039, 11088
```

<img width="513" alt="image" src="https://user-images.githubusercontent.com/32367206/204558855-731975d7-2684-4c59-b8c7-db2016221876.png">

Notice how the first emoji (😊) becomes `65533, 65533` instead of `55357, 56842`. Optimally this should rather be `128522` (the rune of "😊" with the surrogates not being separated).

```
Source runes
128522, 9786, 65039, 128546, 129300, 10084, 65039, 127804, 128077, 129309, 128079, 10004, 65039, 9728, 65039, 11088
Destination runes
65533, 65533, 9786, 65039, 65533, 65533, 65533, 65533, 10084, 65039, 65533, 65533, 65533, 65533, 65533, 65533, 65533, 65533, 10004, 65039, 9728, 65039, 11088
```

But if we cannot have that, it should still support returning the same values. (`55357, 56842` instead of `65533, 65533`). 

In my understanding characters outside of the Basic Multilingual Plane [are composed of _surrogate pairs_](https://api.dart.dev/stable/dart-core/Runes-class.html) which are essentially two 16 bit numbers, but these should be handled together. It looks that the `value!.split('')` what the `rich_clipboard_web`'s `setData` does separates these pairs and this information is lost.

______

Additionally if you uncomment `debugPrint(destinationController.text.characters.toString());` the app crashes with the framework requesting to open an issue. 
```
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: ��☺️����❤️��������✔️☀️⭐
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
```

**Comment by jmatth** [comment]
Hi @harkairt, thanks for the bug report and thorough example. I think I have a fix on the [14-web-grapheme-clusters](https://github.com/BringingFire/rich_clipboard/tree/14-web-grapheme-clusters) branch. Can you pull that code and confirm that it fixes the issue for you? If it does I'll merge it and publish an update to pub shortly.

**Comment by harkairt** [comment]
Thank you for the quick reply @jmatth
Unfortunately, it is still behaving the same.

**Comment by jmatth** [comment]
Hmm, that's odd. I can't reproduce it on my end after those changes. Can you confirm you're on my branch at commit ed6dcd3f6625d35473cd44e0d88cc3b59cbd6d01? The output of the following commands might also help:

```shell
git status -b
```

```shell
flutter doctor
```

**Comment by harkairt** [comment]
I'll check later again, but I surely was depending on the proper commit (pub get has this issue of not updating properly when referencing a git ref, but I removed all the versioned entries from my `~/.pub-cache/hosted/pub.dartlang.org` and then ran `flutter pub get` and even went into the source code and it had the proper commit hash and the changes as well)

may I ask which OS and browser are you using? (it is macos & chrome on my end)

**Comment by jmatth** [comment]
I'm also on macOS with Chrome. I also tested on Safari.

I've been testing by replacing the contents of `main.dart` in the example app with your example code, rather than trying to pull the branch in as a dependency of another project. In my experience pub can do the wrong thing with git overrides in a lot of situations.

I just went ahead and pushed my fix to pub as `rich_clipboard_web` version `1.0.1`. Please test with that version whenever is convenient and if the issue persists I'll reopen this issue and we can debug further.
