### ISSUE TITLE
Unable to build it on Android

### ISSUE THREAD

**Issue by BirjuVachhani** [BringingFire/rich_clipboard#18]
![image](https://user-images.githubusercontent.com/20423471/224985172-3b34705c-c1ed-47b7-b58c-fc64294ea698.png)

**Comment by kostasoft** [comment]
Change  `ext.kotlin_version = '1.8.0'` in build.gradle file please!

**Comment by jmatth** [comment]
Based on other Android plugins, it looks like `ext.kotlin_version` does not have to be specified. To avoid having to push an update every time Flutter changes their upstream version, I've removed `ext.kotlin.version` from `build.gradle` in d5bb2ea35ca4927ffe3f33e7c94e2032c9845cfc and pushed that change to pub.dev as version `1.0.1`. With that change I'm able to build and run the example app, but please let me know if you continue to experience issues after updating.
