### ISSUE TITLE
Upgrade win32 package constraint to "<6.0.0"

### ISSUE THREAD

**Issue by BirjuVachhani** [BringingFire/rich_clipboard#21]
I am getting this error when I run `pub get`. Please update `win32` dependency so it is compatible with other packages that also uses `win32` package.

```console
Because rich_clipboard_windows <1.0.2 depends on win32 ^2.5.1 and no versions of rich_clipboard_windows match >1.0.2 <2.0.0, rich_clipboard_windows <1.0.2-∞ or >1.0.2 <2.0.0 requires win32 ^2.5.1.
And because rich_clipboard_windows 1.0.2 depends on win32 >=2.5.1 <5.0.0, rich_clipboard_windows <2.0.0 requires win32 >=2.5.1 <5.0.0.
Because no versions of rich_clipboard match >1.0.1 <2.0.0 and rich_clipboard 1.0.1 depends on rich_clipboard_windows ^1.0.0, rich_clipboard ^1.0.1 requires rich_clipboard_windows ^1.0.0.
Thus, rich_clipboard ^1.0.1 requires win32 >=2.5.1 <5.0.0.
And because file_picker >=5.3.2 depends on win32 ^5.0.2, rich_clipboard ^1.0.1 is incompatible with file_picker >=5.3.2.
So, because codelessly depends on both file_picker ^5.3.2 and rich_clipboard ^1.0.1, version solving failed.
```

**Comment by BirjuVachhani** [comment]
Any update on this? This is really a blocker for me!

**Comment by jmatth** [comment]
~Unfortunately the new version of win32 depends on Dart 3, which in turn introduced changes to some FFI signatures which are proving hard to debug.~ This was incorrect, the changes to to function signatures are entirely within the win32 package and just use some FFI types as arguments.

For conflicting version constraints in the dependency graph, you can always try to work around it with using [`dependency_overrides`][1].

[1]: https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by BirjuVachhani** [comment]
@jmatth Are you planning to upgrade this to latest version of `win32` package any time soon?

**Comment by jmatth** [comment]
Hi, I have the fix implemented and will push an update later today. Full disclosure: this project is probably going to be deprecated in favor of [super_clipboard][1] sometime in the future. That package already has more features and the team at Superlist has more resources to maintain it.

[1]: https://pub.dev/packages/super_clipboard

**Comment by BirjuVachhani** [comment]
@jmatth Thank you for the update! May. Reasons I don't wanna use super_clipboard.

1. External dependency: It depends on Rust. I have install it separately.
2. NDK requirement for Android.

These are serious red flags for me. Besides rich_clipboard almost has all the functionality I need. I wish this package won't get deprecated but I guess it can't be helped!

Will be waiting for the new release! Thank you!

**Comment by BirjuVachhani** [comment]
@jmatth Did you push the update?

**Comment by jmatth** [comment]
The change is up now as version 1.0.3 of rich_clipboard_windows

**Comment by BirjuVachhani** [comment]
Thanks @jmatth. Kudos!
